export const accountCopy = {
  navLabel: "Account",
  signIn: "Sign In",
  signOut: "Sign Out",
  authPendingNote:
    "Sign in to sync your profile. Orders and downloads on this device stay available after you sign in.",
  overviewEyebrow: "Account",
  overviewHeading: "Welcome Back",
  overviewWelcomePrefix: "Welcome back,",
  overviewBody:
    "Review orders, reopen downloads, and manage preferences from one place.",
  overviewOrders: "My Orders",
  overviewDownloads: "My Downloads",
  overviewSettings: "Account Settings",
  overviewSaved: "Saved Designs",
  overviewRecent: "Recent Order",
  overviewEmptyOrders: "No purchases on this device yet.",
  overviewExplore: "Explore Designs",
  settingsEyebrow: "Account",
  settingsHeading: "Account Settings",
  settingsBody:
    "Manage your personal information, security, and download preferences.",
  profileGuest: "Guest on this device",
  profileLocal: "Signed in on this device",
  profileMemberSince: "Member since",
  profileCheckoutEmail: "Checkout email on this device",
  personalHeading: "Personal Information",
  firstName: "First Name",
  lastName: "Last Name",
  displayName: "Display Name",
  country: "Country",
  countryOptional: "Optional",
  saveChanges: "Save Changes",
  saving: "Saving…",
  saved: "Saved",
  changesSaved: "Your changes have been saved.",
  emailHeading: "Email Address",
  currentEmail: "Current email",
  noEmail: "No email saved on this device yet.",
  emailCheckoutNote: "Shown from your most recent checkout on this device.",
  changeEmail: "Change Email",
  emailPending:
    "Email stays tied to your signed-in account. Contact support to change it.",
  passwordHeading: "Password",
  passwordBody:
    "Update the password for this device account.",
  passwordCurrent: "Current password",
  passwordNext: "New password",
  passwordConfirm: "Confirm new password",
  passwordUpdate: "Update Password",
  passwordUpdating: "Updating…",
  passwordUpdated: "Password updated.",
  passwordInvalidCurrent: "Current password is incorrect.",
  passwordMismatch: "New passwords must match.",
  passwordForgotLink: "Forgot password instead?",
  changePassword: "Update Password",
  securityHeading: "Account Security",
  securityPassword: "Password",
  securityEmail: "Email",
  securitySessions: "Active sessions",
  securityPending: "Pending sign-in",
  securityProtected: "Protected",
  securityVerifiedPending: "Verification pending",
  securitySignedIn: "Signed in on this device",
  securitySessionsPending: "—",
  securitySessionsCurrent: "1",
  lastLoginPending: "Last login for this session.",
  lastLoginToday: "This session",
  sessionsHeading: "Active Sessions",
  sessionsPending:
    "You are signed in on this browser session.",
  sessionsCurrentBody:
    "You’re signed in on this browser.",
  downloadPrefsHeading: "Download Preferences",
  preferredFormat: "Preferred file format",
  formatAll: "Show all available formats",
  rememberFormat: "Remember my preferred format",
  openInstructions: "Automatically open download instructions",
  orderInfoHeading: "Order History",
  viewOrders: "View My Orders",
  viewOrder: "View Order",
  recentOrder: "Recent Order",
  paid: "Paid",
  noOrdersYet: "No completed orders on this device yet.",
  dangerHeading: "Account",
  deleteHeading: "Delete Account",
  deleteBody:
    "Clear local account preferences saved in this browser. Purchase history on this device is managed separately from preferences.",
  deleteAccount: "Delete Account",
  deleteModalHeading: "Clear local preferences?",
  deleteModalBody:
    "This removes profile and download preferences stored in this browser. It does not delete embroidery purchase files from your device history until you clear those separately. Full account deletion policy applies when signed-in accounts are connected.",
  deleteConfirmLabel: "Type DELETE to confirm.",
  deleteConfirmWord: "DELETE",
  cancel: "Cancel",
  ordersEyebrow: "Account",
  ordersHeading: "My Orders",
  ordersBody: "Review purchases made on this device and reopen your downloads.",
  ordersEmptyHeading: "No Orders Yet",
  ordersEmptyBody:
    "When you complete a purchase on this device, it will appear here.",
  orderDetailBack: "Back to Orders",
  orderDetailPaid: "Paid",
  orderDetailDownloadAll: "Download ZIP",
  orderDetailTryAgain: "Try Again",
  orderDetailNeedHelp: "Need help?",
  orderDetailTimelinePurchased: "Purchased",
  orderDetailTimelinePayment: "Payment",
  orderDetailTimelineReady: "Ready",
  orderDetailSummary: "Order Summary",
  orderDetailItems: "Items",
  orderDetailDesigns: "designs",
  orderDetailDesignSingular: "design",
  orderDetailYourDesigns: "Your Designs",
  orderDetailFiles: "Files",
  orderDetailDownloadFormat: "Download",
  orderDetailViewDesign: "View Design",
  orderDetailGuideHeading: "Getting Started",
  orderDetailGuideBody: "Need help using this design?",
  orderDetailViewGuide: "View Download Guide",
  orderDetailLicenseHeading: "License",
  orderDetailLicenseBody:
    "Your purchase includes the license associated with this design.",
  orderDetailViewLicense: "View License",
  orderDetailReceipt: "Receipt",
  orderDetailSubtotal: "Subtotal",
  orderDetailDiscount: "Discount",
  orderDetailTotal: "Total",
  orderDetailSupportHeading: "Need Help?",
  orderDetailSupportBody:
    "Having trouble downloading or using your files?",
  orderDetailContact: "Contact Support",
  orderDetailExplore: "Keep Exploring",
  orderDetailMissingHeading: "Order Not Found",
  orderDetailMissingBody:
    "This order isn’t available in this browser’s purchase history.",
  orderDetailPaymentMethodPending:
    "Payment method details appear when a payment provider is connected.",
  downloadsEyebrow: "Your Library",
  downloadsHeading: "My Downloads",
  downloadsBody:
    "Access the embroidery designs you've purchased, whenever you're ready to create.",
  downloadsSearchLabel: "Search your designs",
  downloadsSearchPlaceholder: "Search your designs…",
  downloadsSortRecent: "Recently Purchased",
  downloadsSortName: "Name A–Z",
  downloadsAllFormats: "All",
  downloadsAllOrders: "All Orders",
  downloadsEmptyHeading: "Your Library Is Empty",
  downloadsEmptyBody: "Purchased embroidery designs will appear here.",
  downloadsExplore: "Explore Designs",
  downloadsPopular: "Popular Designs",
  downloadsPurchased: "Purchased",
  downloadsFormats: "Package",
  downloadsSingleZip: "Single embroidery package (ZIP)",
  downloadsViewOrder: "View Order",
  downloadsViewGuide: "View Guide",
  downloadsLicense: "License",
  downloadsPreparing: "Preparing…",
  downloadsDownloading: "Downloading…",
  downloadsComplete: "Downloaded",
  downloadsStarted: "Download started.",
  downloadsFailed: "Download failed. Try again in a moment.",
  downloadsPendingNote:
    "Download one ZIP with all embroidery files for this design.",
  downloadsUnavailable: "Currently Unavailable",
  downloadsZipAll: "Download ZIP",
  downloadsNoMatch: "No designs match that search.",
} as const;

export const accountCountryOptions = [
  { value: "", label: "Select country" },
  { value: "US", label: "United States" },
  { value: "CA", label: "Canada" },
  { value: "GB", label: "United Kingdom" },
  { value: "AU", label: "Australia" },
  { value: "PK", label: "Pakistan" },
  { value: "DE", label: "Germany" },
  { value: "FR", label: "France" },
  { value: "other", label: "Other" },
] as const;
