export const adminCopy = {
  brand: "Admin",
  sidebarBrand: "Embroidery",
  sidebarMenuGroup: "Menu",
  sidebarAccountHint: "Signed in",
  topBarWorkspace: "Store Admin",
  topBarRole: "Administrator",
  topBarCreate: "Create Design",
  searchPlaceholder: "Search anything…",
  searchPending: "Search the admin catalog.",
  notifications: "Notifications",
  notificationsEmpty: "No notifications yet.",
  notificationsPending: "No admin alerts right now.",
  adminMenu: "Admin",
  signOut: "Sign out",
  productsFileStatusReady: "Ready",
  pendingBackend: "Ready",
  emDash: "—",
  version: "v1.0.0",
  openMenu: "Open navigation",
  closeMenu: "Close navigation",
  sidebarLabel: "Admin",

  overviewTitle: "Overview",
  overviewGreeting: "Welcome to your store overview.",
  overviewBody: "Track catalog health, recent activity, and next actions.",
  overviewRange: "Date range",
  overviewRangePending: "Showing all-time store totals.",
  overviewExport: "Export",
  overviewExportPending: "CSV export coming soon.",
  kpiRevenue: "Revenue",
  kpiOrders: "Orders",
  kpiDesignsSold: "Designs sold",
  kpiDownloads: "Downloads",
  kpiPendingHint: "",
  chartRevenueTitle: "Revenue",
  chartPending:
    "Revenue chart uses live order totals when available.",
  chartMetricRevenue: "Revenue",
  chartMetricOrders: "Orders",
  chartMetricAov: "AOV",
  chartDisabledHint: "Metric toggles unlock with analytics data.",
  dualRevenue: "Revenue",
  dualOrders: "Orders",
  topDesignsTitle: "Top selling designs",
  topDesignsViewAll: "View all",
  topDesignsSales: "Sales",
  topDesignsRevenue: "Revenue",
  topDesignsPending: "Ranked from the live product catalog.",
  topDesignsEmpty: "No catalog designs to rank yet.",
  recentOrdersTitle: "Recent orders",
  recentOrdersViewAll: "View all",
  recentOrdersEmpty:
    "No orders yet. New purchases appear here automatically.",
  fileHealthTitle: "Digital file health",
  fileHealthPending:
    "Formats listed on each product are live in the catalog.",
  fileHealthReview: "Review files",
  insightsTitle: "Business insights",
  insightsCategory: "Best performing category",
  insightsAov: "Average order value",
  insightsPending: "Insights update from live catalog and order data.",
  attentionTitle: "Needs attention",
  attentionAnalytics: "Review recent orders for fulfillment.",
  attentionAuth: "Admin session is active.",
  attentionCms: "CMS settings save to the live API.",
  attentionFiles: "Product formats are managed on each design.",
  attentionResolve: "Resolve",

  productsTitle: "Products",
  productsBody: "Manage your embroidery designs and digital products.",
  productsCreate: "Create Design",
  productsTotal: "Total products",
  productsPublished: "Published",
  productsDrafts: "Drafts",
  productsFileIssues: "File issues",
  productsSearch: "Search products…",
  productsFilterAll: "All",
  productsFilterPublished: "Published",
  productsFilterDraft: "Draft",
  productsFilterUnpublished: "Unpublished",
  productsFilterFileIssue: "File issue",
  productsColProduct: "Product",
  productsColCategory: "Category",
  productsColPrice: "Price",
  productsColFiles: "ZIP",
  productsColSales: "Sales",
  productsColStatus: "Status",
  productsStatusLive: "On storefront",
  productsStatusPublished: "Published",
  productsStatusUnpublished: "Unpublished",
  productsDraftUntilSaved: "Draft until saved",
  productsNameTaken: "A product with this name already exists.",
  productsPublishToggle: "Published on storefront",
  productsPublishToggleHint:
    "When off, this design stays hidden from shoppers until you publish it.",
  productsPublishHint: "Choose whether this design is visible on the storefront.",
  productsEmpty: "No products in the named catalog yet.",
  productsMenuEdit: "Edit",
  productsMenuPreview: "Preview",
  productsMenuDuplicate: "Duplicate",
  productsMenuFiles: "Manage files",
  productsMenuUnpublish: "Unpublish",
  productsMenuPublish: "Publish",
  productsMenuDelete: "Delete",
  productsConfirmDuplicateTitle: "Duplicate design?",
  productsConfirmDuplicateBody:
    "Creates a copy you can edit. The original stays unchanged.",
  productsConfirmDuplicate: "Duplicate",
  productsConfirmUnpublishTitle: "Unpublish design?",
  productsConfirmUnpublishBody:
    "This design will be hidden from the storefront until you publish it again.",
  productsConfirmPublishTitle: "Publish design?",
  productsConfirmPublishBody:
    "This design will appear on the storefront again.",
  productsConfirmPublish: "Publish",
  productsConfirmUnpublish: "Unpublish",
  productsConfirmDeleteTitle: "Delete design?",
  productsConfirmDeleteBody:
    "This permanently removes the design from the catalog.",
  productsConfirmDelete: "Delete",
  productsActionFailed: "Action failed. Try again.",
  productsDuplicated: "Design duplicated.",
  productsNotFound: "This design is not in the named catalog.",
  productsEditorTitle: "Product editor",
  productsCreateTitle: "Create design",
  productsPreview: "Live preview",
  productsSave: "Save",
  productsSaving: "Saving…",
  productsSaved: "Saved",
  productsSavePending: "Changes saved to the catalog.",
  productsUpload: "Upload ZIP",
  productsUploadPending:
    "Upload one confidential embroidery ZIP for this design.",
  productsSectionBasic: "Basic information",
  productsSectionPricing: "Pricing",
  productsSectionCategory: "Category",
  productsSectionImages: "Preview images",
  productsSectionFiles: "Embroidery files",
  productsSectionCompat: "Machine compatibility",
  productsSectionSpecs: "Design specifications",
  productsSectionGuide: "Guide",
  productsSectionLicense: "License",
  productsSectionSeo: "SEO",
  productsSectionPublish: "Publishing",
  productsName: "Name",
  productsDescription: "Description",
  productsCategory: "Category",
  productsPrice: "Price",
  productsFormat: "Package",
  productsVersion: "Version",
  productsSize: "Size",
  productsStitches: "Stitches",
  productsFileStatus: "Status",
  productsFileMetaPending: "Customers receive one ZIP package after purchase.",
  productsPackageReady: "ZIP package ready",
  productsPackageMissing: "No ZIP uploaded yet.",
  productsPackageRequired: "Upload an embroidery ZIP before saving.",
  productsPackageHint:
    "One confidential ZIP per design — up to 20 MB with the embroidery files inside.",
  productsPackageUploading: "Uploading ZIP…",
  productsPackageUploadFailed: "ZIP upload failed. Try another file.",
  productsImageSrc: "Preview image URL",
  productsImageAlt: "Preview image alt",
  productsStitchedSrc: "Stitched image URL",
  productsStitchedAlt: "Stitched image alt",
  productsImageUpload: "Upload image",
  productsImageUploading: "Uploading…",
  productsImageUploadHint: "JPEG, PNG, or WebP up to 4 MB.",
  productsImageUploadFailed: "Image upload failed. Try another file.",
  productsHoopSize: "Hoop size",
  productsStitchCount: "Stitch count",
  productsFormats: "Delivery",
  productsFormatsHint:
    "Customers download one ZIP only. Do not offer separate format downloads.",
  productsZipLabel: "ZIP package",
  productsBadge: "Badge",
  productsRating: "Rating",
  productsCompatHint:
    "Delivery is a single ZIP package — not separate machine-format downloads.",
  productsGuideHint: "Stitch guidance is shown from the design specs on the product page.",
  productsLicenseHint: "Digital designs use the store license terms on checkout.",
  productsSeoHint: "Name and description feed the storefront product page.",
  productsImageRequired: "Preview image URL is required.",
  productsFormatsRequired: "Upload the embroidery ZIP package.",

  categoriesTitle: "Categories",
  categoriesBody: "Manage design categories and store navigation.",
  categoriesCreate: "Create Category",
  categoriesTotal: "Total categories",
  categoriesVisible: "Visible",
  categoriesHidden: "Hidden",
  categoriesSearch: "Search categories.",
  categoriesFilterAll: "All",
  categoriesFilterVisible: "Visible",
  categoriesFilterHidden: "Hidden",
  categoriesColCategory: "Category",
  categoriesColPosition: "Position",
  categoriesColDesigns: "Designs",
  categoriesColStatus: "Status",
  categoriesMoveUp: "Move up",
  categoriesMoveDown: "Move down",
  categoriesReorderFailed: "Could not update category order. Try again.",
  categoriesReordered: "Category order updated.",
  categoriesStatusLive: "Visible",
  categoriesStatusHidden: "Hidden",
  categoriesEmpty: "No categories found.",
  categoriesMenuEdit: "Edit",
  categoriesMenuPreview: "Preview",
  categoriesMenuHide: "Hide",
  categoriesMenuShow: "Show",
  categoriesMenuDelete: "Delete",
  categoriesConfirmHideTitle: "Hide category?",
  categoriesConfirmHideBody:
    "This category will be hidden from the storefront until you show it again.",
  categoriesConfirmShowTitle: "Show category?",
  categoriesConfirmShowBody:
    "This category will appear on the storefront again.",
  categoriesConfirmDeleteTitle: "Delete category?",
  categoriesConfirmDeleteBody:
    "This permanently removes the category. Designs keep their category id until reassigned.",
  categoriesConfirmHide: "Hide",
  categoriesConfirmShow: "Show",
  categoriesConfirmDelete: "Delete",
  categoriesActionPending: "Category changes save to the catalog.",
  categoriesImage: "Category image",
  categoriesImageAlt: "Image alt",
  categoriesImageRequired: "Category image is required for storefront tiles.",
  categoriesActionFailed: "Category action failed. Try again.",

  settingsTitle: "Store Settings",
  settingsBody: "Configure global store preferences, payments, and notifications.",
  settingsSectionGeneral: "General Settings",
  settingsStoreName: "Store Name",
  settingsStoreEmail: "Contact Email",
  settingsSectionPayments: "Payment Gateway",
  settingsCurrency: "Default Currency",
  settingsStripeKey: "Stripe Public Key",
  settingsSectionNotifications: "Email Notifications",
  settingsOrderConfirmation: "Order Confirmation",
  settingsSave: "Save Settings",

  ordersTitle: "Orders",
  ordersBody: "Track purchases, payments, and digital delivery.",
  ordersExport: "Export orders",
  ordersExportPending: "CSV export coming soon.",
  ordersKpiTotal: "Total orders",
  ordersKpiPaid: "Paid",
  ordersKpiRefunded: "Refunded",
  ordersKpiRevenue: "Revenue",
  ordersSearch: "Search order / customer…",
  ordersEmpty: "No orders yet.",
  ordersFilterComingSoon: "Filters refine the list soon.",
  ordersColOrder: "Order",
  ordersColCustomer: "Customer",
  ordersColItems: "Design",
  ordersMoreDesigns: "more",
  ordersDesignCount: "designs",
  ordersColTotal: "Total",
  ordersColPayment: "Payment",
  ordersColDate: "Date",
  ordersColActions: "Actions",
  ordersMenuDelete: "Delete",
  ordersConfirmDeleteTitle: "Delete order?",
  ordersConfirmDeleteBody:
    "This permanently removes the order and its line items.",
  ordersConfirmDelete: "Delete",
  ordersActionFailed: "Could not delete this order. Try again.",
  orderDetailTitle: "Order",
  orderDetailPending: "Order not found.",
  orderDetailCustomer: "Customer",
  orderDetailDesigns: "Purchased designs",
  orderDetailPayment: "Payment",
  orderDetailDelivery: "Digital delivery",
  orderDetailDownloads: "Download activity",
  orderDetailDeliveryReady: "Digital files are available after purchase.",
  orderDetailDownloadsEmpty: "No download events recorded for this order yet.",
  orderDetailRefund: "Issue refund",
  orderDetailRefundPending:
    "Refunds are not enabled for digital orders yet.",
  orderDetailRefundConfirm: "Confirm refund",
  orderDetailRefundCancel: "Cancel",
  orderDetailDelete: "Delete order",
  orderDetailBack: "Back to orders",

  siteTitle: "Dynamic Site",
  siteBody: "Manage the content displayed across your website.",
  sitePreview: "Preview website",
  sitePublish: "Publish changes",
  sitePublishPending: "Changes save immediately to the live CMS.",
  siteOpenGlobal: "Open global settings",
  sitePublishedNow: "Synced with live CMS",
  siteHealthTitle: "Website status",
  siteHealthLive: "Storefront live",
  siteHealthPublished: "Last published",
  siteHealthPublishedPending: "Settings sync when you save each section.",
  siteMapHome: "Home",
  siteMapPages: "Pages",
  siteMapGlobal: "Global",
  siteGlobalSummary: "Header, footer, social links, and contact information.",
  siteHomeTitle: "Homepage",
  siteHomeReorderHint:
    "Reorder sections, then save to publish.",
  siteEdit: "Edit",
  siteHide: "Hide",
  siteDelete: "Delete",
  siteAddFaq: "Add question",
  siteFaqTitle: "FAQ",
  siteFaqPending: "FAQ items save to the live CMS.",
  sitePagesTitle: "Pages",
  siteGlobalTitle: "Global content",
  siteGlobalBrand: "Brand name",
  siteGlobalTagline: "Tagline",
  siteGlobalContact: "Contact information",
  siteGlobalContactHint:
    "Shown on the storefront footer and contact page. Clear a field to remove it.",
  siteGlobalClearContact: "Clear contact",
  siteGlobalEmail: "Contact email",
  siteGlobalEmailPlaceholder: "azamclothdesign@gmail.com",
  siteGlobalPhone: "Phone number",
  siteGlobalPhonePlaceholder: "+92 322 4725253",
  siteGlobalAddress: "Address",
  siteGlobalAddressPlaceholder: "Street, city, country",
  siteGlobalSocial: "Social links",
  siteGlobalEmailPending:
    "Add a support email below to show it on the storefront.",
  siteGlobalInstagram: "Instagram",
  siteGlobalPinterest: "Pinterest",
  siteStickyUnsaved: "Unsaved changes",
  siteStickySaved: "All changes saved",
  siteStickyDiscard: "Discard",
  siteStickyDraft: "Save draft",
  siteStickyPreview: "Preview",
  siteStickyPublish: "Publish",
  siteHeroTitle: "Hero",
  siteHeroEyebrow: "Eyebrow",
  siteHeroHeading: "Heading",
  siteHeroBody: "Body",
  siteHeroCta: "Primary CTA",
  siteHeroUrl: "Primary CTA URL",
  siteHomeEmpty: "No homepage sections loaded yet.",
  siteHomeResetSections: "Load default sections",
  siteMoveUp: "Up",
  siteMoveDown: "Down",
  siteShow: "Show",
  siteSectionPending: "Edit pages and save to the live CMS.",

  securityTitle: "Security",
  securityBody:
    "Protect your admin account and monitor administrative activity.",
  securityStatusPending: "Admin authenticated",
  securityStatusLive: "Admin authenticated",
  securityScoreLabel: "Security",
  securityScoreValue: "Protected",
  securityScoreHint:
    "Admin login, HMAC API signing, and session cookies are active.",
  securityAccount: "Admin account",
  securityName: "Name",
  securityEmail: "Email",
  securityPassword: "Password",
  securityPasswordPending: "Use a strong unique password for this admin account.",
  securityChangePassword: "Change password",
  security2fa: "Two-factor authentication",
  security2faPending: "Two-factor authentication is not required for local admin yet.",
  security2faEnable: "Enable 2FA",
  securitySessions: "Active sessions",
  securitySessionsEmpty:
    "You are signed in on this browser session.",
  securitySignOutOthers: "Sign out other sessions",
  securityActivity: "Security activity",
  securityActivityEmpty: "Sign-in activity is protected by HMAC and session cookies.",
  securityAdminActivity: "Admin activity",
  securityControls: "Security controls",
  securityControlAuth: "Admin authentication",
  securityControl2fa: "2FA",
  securityControlSession: "Session protection",
  securityControlDownload: "Download protection",
  securityControlAudit: "Audit logging",
  securityControlPending: "Pending",
  securityControlActive: "Active",
  securityDanger: "Danger zone",
  securityDangerBody:
    "Force every administrator session to authenticate again.",
  securityDangerAction: "Sign out all sessions",
  securityDangerPending:
    "Signing out clears this admin session.",
  confirmClose: "Close",
} as const;

export const adminHomeSections = [
  { id: "hero", label: "Hero" },
  { id: "categories", label: "Categories" },
  { id: "social-proof", label: "Social proof" },
  { id: "problem-solution", label: "Problem / Solution" },
  { id: "how-it-works", label: "How it works" },
  { id: "faq", label: "FAQ" },
  { id: "final-cta", label: "Final CTA" },
] as const;

export const adminSitePages = [
  { id: "about", label: "About", href: "/about" },
  { id: "how-it-works", label: "How it works", href: "/how-it-works" },
  { id: "contact", label: "Contact", href: "/contact" },
  { id: "licensing", label: "Licensing", href: "/licensing" },
  { id: "help-center", label: "Help center", href: "/help-center" },
] as const;

export const adminHeroDefaults = {
  eyebrow: "Digital embroidery designs",
  heading: "Designs Made to Be Stitched.",
  description:
    "Professionally digitized embroidery designs — one confidential ZIP per design, ready to download and stitch.",
  primaryCta: "Explore Designs",
  primaryUrl: "/designs",
  secondaryCta: "How It Works",
  secondaryUrl: "/how-it-works",
} as const;
