export const authCopy = {
  loginEyebrow: "Account",
  loginHeading: "Sign In",
  loginBody: "Sign in to open your orders, downloads, and account settings.",
  loginSubmit: "Sign In",
  loginSubmitting: "Signing in…",
  loginError: "That email or password doesn’t match an account on this device.",
  loginNoAccount: "Don’t have an account?",
  createAccount: "Create Account",
  forgotLink: "Forgot password?",
  registerEyebrow: "Account",
  registerHeading: "Create Account",
  registerBody:
    "Create an account on this device to save your profile and open My Account after sign-in.",
  registerSubmit: "Create Account",
  registerSubmitting: "Creating account…",
  registerExists: "An account with that email already exists on this device.",
  registerHasAccount: "Already have an account?",
  signInLink: "Sign in",
  forgotEyebrow: "Account",
  forgotHeading: "Forgot Password",
  forgotBody:
    "Enter the email for your account on this device. You can set a new password here when the email matches.",
  forgotContinue: "Continue",
  forgotResetHeading: "Choose a New Password",
  forgotResetSubmit: "Update Password",
  forgotResetSubmitting: "Updating…",
  forgotMissing: "No account with that email was found on this device.",
  forgotSuccess: "Password updated. You can sign in now.",
  backToSignIn: "Back to Sign In",
  email: "Email",
  password: "Password",
  confirmPassword: "Confirm Password",
  firstName: "First Name",
  lastName: "Last Name",
  passwordHint: "Use at least 8 characters.",
  passwordStrength: "Password strength",
  required: "This field is required.",
  invalidEmail: "Enter a valid email address.",
  passwordMismatch: "Passwords must match.",
  passwordTooShort: "Password must be at least 8 characters.",
  deviceNote:
    "Sign in to sync your cart, wishlist, and order history across devices.",
  gateHeading: "Sign In to Continue",
  gateBody:
    "My Account is available after you sign in or create an account.",
  gateSignIn: "Sign In",
  gateRegister: "Create Account",
  signedOut: "You’ve been signed out.",
} as const;
