import { type ShopCategoryId } from "@/constants/shopCatalog";

export type BestSeller = {
  slug: string;
  name: string;
  categoryId: ShopCategoryId;
  rating: number;
  formats: readonly string[];
  priceCents: number;
  imageSrc: string;
  imageAlt: string;
  stitchedImageSrc?: string;
  stitchedImageAlt?: string;
};

export const bestSellers: readonly BestSeller[] = [
  {
    slug: "design-one",
    name: "Design One",
    categoryId: "wilcom-embroidery-software",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/designOne.jfif",
    imageAlt: "Design One embroidery design",
    stitchedImageSrc: "/assets/images/designOne.jfif",
    stitchedImageAlt: "Design One stitched design",
  },
  {
    slug: "design-two",
    name: "Design Two",
    categoryId: "embroidery-digitizing-course",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/designTwo.jpeg",
    imageAlt: "Design Two embroidery design",
    stitchedImageSrc: "/assets/images/designTwo.jpeg",
    stitchedImageAlt: "Design Two stitched design",
  },
  {
    slug: "design-three",
    name: "Design Three",
    categoryId: "step-by-step-embroidery-digitizing-guide",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/designThree.webp",
    imageAlt: "Design Three embroidery design",
    stitchedImageSrc: "/assets/images/designThree.webp",
    stitchedImageAlt: "Design Three stitched design",
  },
  {
    slug: "design-four",
    name: "Design Four",
    categoryId: "cap-cart-embroidery",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/designFour.jfif",
    imageAlt: "Design Four embroidery design",
    stitchedImageSrc: "/assets/images/designFour.jfif",
    stitchedImageAlt: "Design Four stitched design",
  },
  {
    slug: "design-five",
    name: "Design Five",
    categoryId: "anarkali-kurti-shirt-embroidery",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/designFive.jfif",
    imageAlt: "Design Five embroidery design",
    stitchedImageSrc: "/assets/images/designFive.jfif",
    stitchedImageAlt: "Design Five stitched design",
  },
  {
    slug: "design-six",
    name: "Design Six",
    categoryId: "maxi-lehenga-embroidery",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/designSix.jfif",
    imageAlt: "Design Six embroidery design",
    stitchedImageSrc: "/assets/images/designSix.jfif",
    stitchedImageAlt: "Design Six stitched design",
  },
  {
    slug: "design-seven",
    name: "Design Seven",
    categoryId: "sherwani-embroidery",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/designSeven.jpg",
    imageAlt: "Design Seven embroidery design",
    stitchedImageSrc: "/assets/images/designSeven.jpg",
    stitchedImageAlt: "Design Seven stitched design",
  },
  {
    slug: "design-eight",
    name: "Design Eight",
    categoryId: "shawl-embroidery",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/designEight.jpg",
    imageAlt: "Design Eight embroidery design",
    stitchedImageSrc: "/assets/images/designEight.jpg",
    stitchedImageAlt: "Design Eight stitched design",
  },
  {
    slug: "design-nine",
    name: "Design Nine",
    categoryId: "neckline-embroidery",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/designNine.jfif",
    imageAlt: "Design Nine embroidery design",
    stitchedImageSrc: "/assets/images/designNine.jfif",
    stitchedImageAlt: "Design Nine stitched design",
  },
  {
    slug: "design-ten",
    name: "Design Ten",
    categoryId: "gala-daman-embroidery",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/designTen.jpg",
    imageAlt: "Design Ten embroidery design",
    stitchedImageSrc: "/assets/images/designTen.jpg",
    stitchedImageAlt: "Design Ten stitched design",
  },
  {
    slug: "design-eleven",
    name: "Design Eleven",
    categoryId: "gala-daman-sequins-embroidery",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/designEleven.jfif",
    imageAlt: "Design Eleven embroidery design",
    stitchedImageSrc: "/assets/images/designEleven.jfif",
    stitchedImageAlt: "Design Eleven stitched design",
  },
  {
    slug: "butter-radiance",
    name: "Butter Radiance",
    categoryId: "all-over-embroidery",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/butterRadiance.webp",
    imageAlt: "Butter Radiance embroidery design",
    stitchedImageSrc: "/assets/images/butterRadiance.webp",
    stitchedImageAlt: "Butter Radiance stitched design",
  },
  {
    slug: "iznik-maxi-frock",
    name: "Iznik Maxi Frock",
    categoryId: "motif-embroidery",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/iznikMaxiFrock.webp",
    imageAlt: "Iznik Maxi Frock embroidery design",
    stitchedImageSrc: "/assets/images/iznikMaxiFrock.webp",
    stitchedImageAlt: "Iznik Maxi Frock stitched design",
  },
  {
    slug: "sapphire-sun-azure",
    name: "Sapphire Sun Azure",
    categoryId: "velvet-embroidery",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/sapphireSunAzure.webp",
    imageAlt: "Sapphire Sun Azure embroidery design",
    stitchedImageSrc: "/assets/images/sapphireSunAzure.webp",
    stitchedImageAlt: "Sapphire Sun Azure stitched design",
  },
  {
    slug: "whats-app-image",
    name: "WhatsApp Image",
    categoryId: "cotton-embroidery",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/whatsAppImage.jpeg",
    imageAlt: "WhatsApp Image embroidery design",
    stitchedImageSrc: "/assets/images/whatsAppImage.jpeg",
    stitchedImageAlt: "WhatsApp Image stitched design",
  },
  {
    slug: "bd2506b",
    name: "BD 2506B",
    categoryId: "shaneel-embroidery",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/bd2506b.webp",
    imageAlt: "BD 2506B embroidery design",
    stitchedImageSrc: "/assets/images/bd2506b.webp",
    stitchedImageAlt: "BD 2506B stitched design",
  },
  {
    slug: "images-two",
    name: "Images Two",
    categoryId: "aari-embroidery",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/imagesTwo.jfif",
    imageAlt: "Images Two embroidery design",
    stitchedImageSrc: "/assets/images/imagesTwo.jfif",
    stitchedImageAlt: "Images Two stitched design",
  },
  {
    slug: "stardom-elaf-lime",
    name: "Stardom Elaf Lime",
    categoryId: "dori-embroidery",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/stardomElafLime.webp",
    imageAlt: "Stardom Elaf Lime embroidery design",
    stitchedImageSrc: "/assets/images/stardomElafLime.webp",
    stitchedImageAlt: "Stardom Elaf Lime stitched design",
  },
  {
    slug: "stardom-elaf-glamorous",
    name: "Stardom Elaf Glamorous",
    categoryId: "fancy-lace-embroidery",
    rating: 4.9,
    formats: ["PES", "DST", "JEF"],
    priceCents: 499,
    imageSrc: "/assets/images/stardomElafGlamorous.webp",
    imageAlt: "Stardom Elaf Glamorous embroidery design",
    stitchedImageSrc: "/assets/images/stardomElafGlamorous.webp",
    stitchedImageAlt: "Stardom Elaf Glamorous stitched design",
  },
];
