export const cartCopy = {
  eyebrow: "Your collection",
  heading: "Your Cart",
  body: "Review your embroidery designs before continuing to secure checkout.",
  progressCart: "Cart",
  progressCheckout: "Checkout",
  progressDownload: "Download",
  yourDesigns: "Your Designs",
  orderSummary: "Order Summary",
  subtotal: "Subtotal",
  discount: "Discount",
  total: "Total",
  checkout: "Proceed to Checkout",
  checkoutLoading: "Preparing secure checkout...",
  securePayment: "Secure payment",
  instantDelivery: "Instant digital delivery",
  downloadAfter: "Download files after purchase",
  digitalNotice:
    "Digital products only. No physical item will be shipped. Your embroidery files and included guides will be available after successful payment.",
  secureCheckout: "Secure Checkout",
  secureBody: "Your payment information is securely processed.",
  continueShopping: "Continue Shopping",
  remove: "Remove",
  saveForLater: "Save for Later",
  instantDownload: "Instant Download",
  havePromo: "Have a promo code?",
  promoPlaceholder: "Enter promo code",
  apply: "Apply",
  promoInvalid: "That code isn't valid or has expired.",
  removedToast: "Design removed.",
  undo: "Undo",
  wishlistToast: "Added to your wishlist",
  emptyEyebrow: "Nothing here yet",
  emptyHeading: "Your Next Project Starts With a Design.",
  emptyBody:
    "Explore our collection of professionally digitized embroidery designs and find something worth stitching.",
  exploreDesigns: "Explore Designs",
  browsePopular: "Browse Popular Designs",
  exploreEyebrow: "Not sure what to stitch next?",
  exploreHeading: "Complete Your Project",
  exploreBody:
    "Browse the collection for designs that pair with what you're stitching now.",
  trustDownloadHeading: "Instant Download",
  trustDownloadBody: "Access your files immediately after payment.",
  trustFormatsHeading: "One ZIP Package",
  trustFormatsBody: "Download a single embroidery ZIP for each design after payment.",
  trustHelpHeading: "Help When You Need It",
  trustHelpBody: "Support is available if you need help with your order or download.",
  somethingChanged: "Something Changed",
  somethingChangedBody:
    "One or more designs in your cart are no longer available. Please review your cart before continuing.",
  reviewCart: "Review Cart",
  embroideryDesign: "Embroidery Design",
} as const;

export const cartTrustItems = [
  {
    heading: cartCopy.trustDownloadHeading,
    body: cartCopy.trustDownloadBody,
  },
  {
    heading: cartCopy.trustFormatsHeading,
    body: cartCopy.trustFormatsBody,
  },
  {
    heading: cartCopy.trustHelpHeading,
    body: cartCopy.trustHelpBody,
  },
] as const;
