export const checkoutCopy = {
  secureCheckout: "Secure Checkout",
  eyebrow: "Secure checkout",
  heading: "Complete Your Purchase",
  body: "You're one step away from accessing your embroidery designs.",
  progressCart: "Cart",
  progressCheckout: "Checkout",
  progressDownload: "Download",
  yourInformation: "Your Information",
  emailLabel: "Email address",
  emailHint: "Your download link and order confirmation will be sent to this email.",
  emailValid: "Email looks good",
  emailInvalid: "Please enter a valid email address.",
  signInPrompt: "Already have an account?",
  signIn: "Sign in",
  accountAfter:
    "Create an account after checkout to manage your downloads and orders.",
  paymentHeading: "Payment",
  paymentSecure: "Secure payment",
  paymentMethod: "Payment Method",
  paymentCard: "Card",
  paymentProviderPending:
    "Your payment provider's secure checkout will appear here once it is connected. Card details are never entered on this page until then.",
  paymentReadyHint: "We'll process payment through your connected provider.",
  yourOrder: "Your Order",
  subtotal: "Subtotal",
  discount: "Discount",
  total: "Total",
  digitalDownload: "Digital Download",
  digitalBody:
    "Your files will be available immediately after successful payment. No physical product will be shipped.",
  includedHeading: "Included With Your Purchase",
  includedFiles: "Embroidery files",
  includedFormats: "Single embroidery ZIP",
  includedSpecs: "Design specifications",
  includedGuide: "Order download access",
  havePromo: "Have a promo code?",
  promoPlaceholder: "Enter promo code",
  apply: "Apply",
  promoInvalid: "That code isn't valid or has expired.",
  termsLabel:
    "I agree to the Terms & Conditions and understand this is a digital product.",
  terms: "Terms",
  privacy: "Privacy",
  licensing: "Licensing",
  paySecurely: "Pay",
  paySecurelySuffix: "Securely",
  processing: "Processing Payment…",
  paymentFailed: "Payment failed — Try Again",
  paymentFailedHeading: "Payment Couldn't Be Completed",
  paymentFailedBody:
    "We couldn't complete your payment. Your order has not been charged.",
  tryAgain: "Try Payment Again",
  securePayment: "Secure Payment",
  secureBody:
    "Your payment information is securely processed by our payment provider.",
  trustInstant: "Instant digital access",
  trustDelivered: "Files delivered after payment",
  trustNoShip: "No physical shipping",
  trustSupport: "Customer support available",
  viewOrderDetails: "View Order Details",
  emptyHeading: "Your cart is empty",
  emptyBody: "Add a design before completing checkout.",
  returnToCart: "Return to Cart",
  returnToShop: "Explore Designs",
  confirmed: "Payment Confirmed",
  preparing: "Preparing Your Downloads…",
  successHeading: "You're Ready to Stitch",
  successBody:
    "When live payments are connected, your embroidery files will appear here immediately after a successful charge.",
  successDownloads: "Go to Downloads",
  backHome: "Back to Home",
} as const;

export const checkoutTrustItems = [
  checkoutCopy.trustInstant,
  checkoutCopy.trustDelivered,
  checkoutCopy.trustNoShip,
  checkoutCopy.trustSupport,
] as const;

export const checkoutIncludedItems = [
  checkoutCopy.includedFiles,
  checkoutCopy.includedFormats,
  checkoutCopy.includedSpecs,
  checkoutCopy.includedGuide,
] as const;
