export const checkoutCopy = {
  secureCheckout: "Secure Checkout",
  eyebrow: "Pay, then get your ZIP",
  heading: "Complete Payment to Download",
  body: "Pay securely now. Your embroidery ZIP files unlock instantly after payment — nothing is shipped.",
  progressCart: "Cart",
  progressCheckout: "Pay",
  progressDownload: "Get ZIP",
  yourInformation: "Your Information",
  contactHeading: "Contact Information",
  contactBody:
    "Enter your contact details so we can confirm your order and ZIP download access.",
  contactNameLabel: "Full name",
  contactNameInvalid: "Please enter your full name.",
  phoneLabel: "Phone number",
  phoneInvalid: "Please enter a valid phone number.",
  contactHint:
    "We use your email for the ZIP download link and order confirmation. Your phone helps us reach you about the order if needed.",
  emailLabel: "Email address",
  emailHint:
    "We’ll send your order confirmation and ZIP download access to this email.",
  emailValid: "Email looks good",
  emailInvalid: "Please enter a valid email address.",
  signInPrompt: "Already have an account?",
  signIn: "Sign in",
  accountAfter:
    "Create an account after checkout to manage your downloads and orders.",
  paymentHeading: "Payment",
  paymentSecure: "Secure payment",
  paymentMethod: "Payment Method",
  paymentCard: "Card",
  paymentProviderPending:
    "Your payment provider's secure checkout will appear here once it is connected. Card details are never entered on this page until then.",
  paymentReadyHint: "We'll process payment through your connected provider.",
  yourOrder: "Your Order",
  subtotal: "Subtotal",
  discount: "Discount",
  total: "Total",
  digitalDownload: "Pay → Get ZIP",
  digitalBody:
    "After successful payment, download one embroidery ZIP for each design immediately. No physical product is shipped.",
  includedHeading: "Included With Your Purchase",
  includedFiles: "Embroidery files",
  includedFormats: "Single embroidery ZIP per design",
  includedSpecs: "Design specifications",
  includedGuide: "Instant download access after payment",
  havePromo: "Have a promo code?",
  promoPlaceholder: "Enter promo code",
  apply: "Apply",
  promoInvalid: "That code isn't valid or has expired.",
  termsLabel:
    "I agree to the Terms & Conditions and understand this is a digital product — I pay, then download a ZIP.",
  terms: "Terms",
  privacy: "Privacy",
  licensing: "Licensing",
  paySecurely: "Pay",
  paySecurelySuffix: "Securely",
  processing: "Processing Payment…",
  paymentFailed: "Payment failed — Try Again",
  paymentFailedHeading: "Payment Couldn't Be Completed",
  paymentFailedBody:
    "We couldn't complete your payment. Your order has not been charged.",
  tryAgain: "Try Payment Again",
  securePayment: "Secure Payment",
  secureBody:
    "Your payment information is securely processed by our payment provider.",
  trustInstant: "Pay once",
  trustDelivered: "Get ZIP instantly",
  trustNoShip: "No physical shipping",
  trustSupport: "Customer support available",
  viewOrderDetails: "View Order Details",
  emptyHeading: "Your cart is empty",
  emptyBody: "Add a design before completing checkout.",
  returnToCart: "Return to Cart",
  returnToShop: "Explore Designs",
  confirmed: "Payment Confirmed",
  preparing: "Preparing Your Downloads…",
  successHeading: "You're Ready to Stitch",
  successBody:
    "When live payments are connected, your embroidery files will appear here immediately after a successful charge.",
  successDownloads: "Go to Downloads",
  backHome: "Back to Home",
} as const;

export const checkoutTrustItems = [
  checkoutCopy.trustInstant,
  checkoutCopy.trustDelivered,
  checkoutCopy.trustNoShip,
  checkoutCopy.trustSupport,
] as const;

export const checkoutIncludedItems = [
  checkoutCopy.includedFiles,
  checkoutCopy.includedFormats,
  checkoutCopy.includedSpecs,
  checkoutCopy.includedGuide,
] as const;
