export const orderSuccessCopy = {
  eyebrow: "Order confirmed",
  heading: "You're Ready to Stitch.",
  body: "Your payment was successful and your embroidery files are ready to download.",
  paymentConfirmed: "Payment Confirmed",
  filesReady: "Files Ready",
  confirmationSent: "Confirmation sent to",
  downloadsHeading: "Your Designs Are Ready",
  downloadsBody: "Download your embroidery files and included guides below.",
  filesIncluded: "Files Included",
  downloadAll: "Download ZIP",
  downloadZip: "Download ZIP",
  downloadFormat: "Download",
  preparing: "Preparing Files…",
  downloading: "Downloading…",
  downloaded: "Downloaded",
  downloadStarted: "Download Started",
  downloadFailed: "Download failed. Try again.",
  tryAgain: "Try Again",
  downloadPendingNote:
    "Your purchase includes one ZIP with all embroidery files for this design.",
  accountAccessNote:
    "You can return to these downloads anytime from My Account.",
  availableFormats: "Available Formats",
  singleZipLabel: "Single embroidery package (ZIP)",
  guideHeading: "Your Embroidery Guide",
  guideBody:
    "Need a little help getting started? Your guide includes the design specifications, color sequence, recommended hoop size, and stitching information.",
  viewGuide: "View Guide",
  downloadGuide: "Download Guide PDF",
  guideTopics: [
    "Design Specifications",
    "Color Sequence",
    "Recommended Materials",
    "Stitching Instructions",
  ] as const,
  nextHeading: "Ready to Start?",
  nextDownload: "Download",
  nextDownloadBody:
    "Choose the format compatible with your embroidery machine.",
  nextTransfer: "Transfer",
  nextTransferBody:
    "Move the file to your machine using your usual USB, software, or transfer method.",
  nextStitch: "Stitch",
  nextStitchBody: "Load your design, prepare your fabric, and bring it to life.",
  machineHeading: "Not Sure Which Format You Need?",
  machineBody: "Find the embroidery format compatible with your machine.",
  machineCta: "Find My Machine",
  orderDetails: "Order Details",
  orderNumber: "Order Number",
  date: "Date",
  status: "Status",
  statusPaid: "Paid",
  email: "Email",
  total: "Total",
  supportHeading: "Need a Hand?",
  supportBody:
    "If you're having trouble downloading your files or aren't sure which format to use, we're here to help.",
  contactSupport: "Contact Support",
  downloadHelp: "Read Download Help",
  accountHeading: "Keep Your Designs in One Place",
  accountBody:
    "Create an account to access your orders, downloads, and future purchases from one place.",
  createAccount: "Create Your Account",
  continueWithout: "Continue Without Account",
  emailReassurancePrefix: "We've also sent your order confirmation and download information to",
  resendEmail: "Didn't receive it? Resend Email",
  resendQueued: "A fresh confirmation email is on the way when available.",
  relatedHeading: "Looking for Your Next Stitch?",
  relatedBody: "Explore more designs that fit the projects you're stitching now.",
  exploreDesigns: "Explore More Designs",
  shareHeading: "We'd Love to See What You Create.",
  shareBody:
    "Stitch your design, share your finished project, and inspire the next creator.",
  shareCta: "Share Your Project",
  finalHeading: "Your Next Project Is Waiting.",
  finalBody:
    "Explore more professionally digitized embroidery designs for your next creation.",
  finalPrimary: "Explore Designs",
  finalSecondary: "Go to My Orders",
  myAccount: "My Account",
  unauthorizedHeading: "We Couldn't Open Those Downloads",
  unauthorizedBody:
    "Download access is tied to a verified purchase. Return from checkout after payment, or open the order from My Account.",
  backToShop: "Explore Designs",
  backToHome: "Back to Home",
} as const;

export const orderSuccessNextSteps = [
  {
    id: "01",
    title: orderSuccessCopy.nextDownload,
    body: orderSuccessCopy.nextDownloadBody,
  },
  {
    id: "02",
    title: orderSuccessCopy.nextTransfer,
    body: orderSuccessCopy.nextTransferBody,
  },
  {
    id: "03",
    title: orderSuccessCopy.nextStitch,
    body: orderSuccessCopy.nextStitchBody,
  },
] as const;
